projects:
  app:
    schemaPath: src/schema.grapqhl
    extensions:
    endpoints:
    default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: src/database/prisma.yml